name : Lancement des tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps: #Etapes à réaliser sur le système
      #On se place dans le dépôt...
      - name: Checkout
        uses: actions/checkout@v3

        #...on installe Java...
      - name: Set up Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

        #...et on lance le script de test
      - name: Run tests
        run: mvn test

